### ISSUE TITLE
Using random within snippets

### ISSUE THREAD

**Issue by be-codified** [jrebocho/vscode-random#20]
Hi,

I am trying to use plugin inside of snippet

    "Test snippet": {
      "prefix": "test-snippet",
      "body": [
        "${RandomShort} and ${RandomShort} and another ${RandomShort}"
      ],
      "description": "Test snippet"
    },

and result is `36850 and 3293 and another 54517` instead of `36850 and 36850 and another 36850`. 

Can this be avoided somehow? Thank you in advance.

**Comment by jrebocho** [comment]
Hi @be-codified,

Unfortunately, the way the extension works, it will generate a new random value every time. That behaviour is intentional.

The reason for this is multi cursors. This way, if we have several cursors at once we can generate different random values for each cursor, instead of always the same value.

I will evaluate adding a config that can be used to toggle this, but that would mean that with multi cursors you will get the same value in each one, not only in snippets.

Thank you for your suggestion!
